"""
Django settings for endsem project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Use PyMySQL as the MySQL driver (also aliased to MySQLdb so Django's mysql
# backend works without needing system C libraries such as mysqlclient).
try:
    import pymysql
    pymysql.install_as_MySQLdb()

    # PyMySQL emulates the legacy mysqlclient API but reports version 1.4.6,
    # which Django 6 rejects (it requires mysqlclient >= 2.2.1). The rest of
    # the mysqlclient API that Django uses is implemented by PyMySQL, so only
    # the reported version needs to be faked.
    import MySQLdb
    MySQLdb.version_info = (2, 2, 1, 'final', 0)
    MySQLdb.__version__ = '2.2.1'
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(key, default=False):
    return os.environ.get(key, str(default)).lower() in ('1', 'true', 'yes', 'on')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-i815%6jce1iwb*(e097!)5blqmgiw8&9-aklzrt=2i=-7v=4^k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'endsem.whitenoise_media.MediaWhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'endsem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'frontend' / 'dist',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'endsem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Local dev uses SQLite by default. In production set DATABASE_URL to a MySQL
# connection string (e.g. Aiven) like:
#   mysql://USER:PASSWORD@HOST:PORT/DBNAME
# and, if the provider requires TLS, set DB_SSL_CA_PATH to a CA certificate file
# (Aiven certs validate against the system bundle, so /etc/ssl/certs/ca-certificates.crt
# works on most Linux hosts).

def _mysql_config_from_url(url):
    from urllib.parse import urlparse
    u = urlparse(url)
    config = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': u.path.lstrip('/'),
        'USER': u.username,
        'PASSWORD': u.password,
        'HOST': u.hostname,
        'PORT': u.port or 3306,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 15,
            'read_timeout': 60,
            'write_timeout': 60,
        },
    }
    # Always encrypt the connection (Aiven requires TLS). Skip certificate
    # verification because Aiven signs service certs with its own CA, which is
    # not present in system CA bundles; DB_SSL_CA_PATH is accepted for
    # compatibility but Aiven's cert cannot be verified against system CAs.
    config['OPTIONS']['ssl'] = {'verify_mode': False}
    return config


DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': _mysql_config_from_url(DATABASE_URL),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

CORS_ALLOWED_ORIGINS = [o for o in os.environ.get(
    'DJANGO_CORS_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
).split(',') if o]

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'home' / 'static',
    BASE_DIR / 'frontend' / 'dist',
]
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Cache media/static responses in the browser for a day so navigating or
# reloading doesn't re-download images on the free instance.
WHITENOISE_MAX_AGE = 86400

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'