# Generated by Django 6.0.1 on 2026-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
